# Generated by Django 3.2.9 on 2021-12-15 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('skill_level', models.CharField(choices=[('0', 'Beginner'), ('1', 'Skilled'), ('2', 'Specialist'), ('3', 'Expert')], default='', max_length=1, verbose_name='Skill Level')),
                ('strength_level', models.CharField(choices=[('5', 'Up to 5% alcohol'), ('7', 'Up to 7% alcohol'), ('12', 'Up to 12% alcohol'), ('40', 'Up to 40% alcohol')], default='', max_length=2, verbose_name='Strength')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites', models.ManyToManyField(to='cocktails_app.Cocktail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('ingredient_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cocktails_app.ingredientcategory')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='cocktail_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cocktails_app.cocktailcategory'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='flavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cocktails_app.flavor'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(to='cocktails_app.Ingredient'),
        ),
    ]
